basePath: /
definitions:
  dto.ConfirmRequest:
    properties:
      code:
        type: integer
      email:
        type: string
    required:
    - code
    - email
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Service that handles authorization and authentication and generates
    jwt token
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Authorization service
  version: "1.0"
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user in the system
      parameters:
      - description: User registration request
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully registered
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Register a new user
      tags:
      - Auth
  /v1/auth/confirm:
    post:
      consumes:
      - application/json
      description: Confirm user by code
      parameters:
      - description: User Confirm request
        in: body
        name: refreshRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User Confirmed
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Confirm user
      tags:
      - Auth
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and obtain an access token
      parameters:
      - description: User login request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Access token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User login
      tags:
      - Auth
  /v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Create new access token by refresh token
      parameters:
      - description: User refresh request
        in: body
        name: refreshRequest
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Access token
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User refresh token
      tags:
      - Auth
schemes:
- http
swagger: "2.0"
