linters-settings:
  gci:
    local-prefixes: github.com/evrone/blockchain
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 65
    statements: 40
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
  gofumpt:
    extra-rules: true
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gochecknoinits
    - goconst
    - godox
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - govet
    - makezero
    - misspell
    - nakedret
    - nlreturn
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

# disable:
#    - exhaustivestruct
#    - ifshort
#    - goheader
#    - prealloc
#    - testpackage
#    - wrapcheck

issues:
  exclude-rules:
    - path: integration-test
      linters:
        - paralleltest
        - godot
    - path: internal/controller/http
      linters:
        - godot

run:
  skip-dirs:
    - docs
